title: YXZ's Blog
# subtitle: "A fast, simple & powerful blog framework powered by Node.js."
# description: "Hexo is a fast, simple & powerful blog framework powered by Node.js."
author: Hexo
language: zh-cn
timezone: UTC

math:
  engine: 'mathjax' # or 'katex'
  # engine: 'katex'
  mathjax:
    src: "//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
    config:
      # MathJax config
       tex2jax: 
        inlineMath: [ ['$','$'], ["\\(","\\)"] ]
        skipTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code']
        processEscapes: true
  katex:
    css: "https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.5.1/katex.min.css"
    js: "https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.5.1/katex.min.js"
    config:
      throwOnError: false
      errorColor: "#cc0000"

# url: https://hexo.io
# root: /public/
url: https://yaoxuanzhi.github.io
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0

theme: navy

deploy:
  type: git
  repo: git@github.com:YaoXuanZhi/YaoXuanZhi.github.io.git
  branch: master

highlight:
  enable: true
  line_number: false


