<!-- GitHub star -->
<a class="github-button" href="https://github.com/YaoXuanZhi/site" data-icon="octicon-star" data-show-count="true" aria-label="Star YaoXuanZhi/site on GitHub">Star</a>
<!-- GitHub fork -->
<a class="github-button" href="https://github.com/YaoXuanZhi/site/fork" data-icon="octicon-repo-forked" data-show-count="true" aria-label="Fork YaoXuanZhi/site on GitHub">Fork</a><!-- Tweet button -->
<!-- Github Button -->
<script async defer src="https://buttons.github.io/buttons.js"></script>
<!-- Twitter share button -->
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
